### ISSUE TITLE
does it use monero v9 ?

### ISSUE THREAD

**Issue by sherifomran** [Luccifer/XMinerClient#1]
do you use monero v9?

**Comment by Luccifer** [comment]
Actually that was educational project for me and I have no idea about the version. But Miner worked with all popular pool-platforms that time, dunno about today, give it a shot and check if u want :)

**Comment by sherifomran** [comment]
i ve a small educational wish and i think i will play with it and i hope to support me along my educational path.

**Comment by Luccifer** [comment]
Fell free to give it a shot ;)
