### ISSUE TITLE
Your framework obsolete

### ISSUE THREAD

**Issue by Glym143** [Luccifer/XMinerClient#2]
hi i have been trying for a very long time to install your project.  I download 4 different versions of Xcode.  I tried to put an old version of Mac OS X on a virtual machine but all attempts were unsuccessful.  Your Framework is out of date.  I get an error.  Module compiled with Swift 4.0.2 cannot be imported by the Swift 4.2 compiler. Please update it, or drop the framework project so I can do it myself.  thank you very much for your reply!  Really looking forward to your reaction. ;)

**Comment by Glym143** [comment]
Or “ Module compiled with Swift 4.0.2 cannot be imported by the Swift 5.0 compiler”. Please update, Bro ;)

**Comment by Luccifer** [comment]
Hey!
Gonna keep an eye on it in two days, gotta a lot of work to be done. In two days at least I will research what is out of date and will update it!
Ty for mention!

**Comment by Glym143** [comment]
OK thank you very much!  Really looking forward to ;)

**Comment by Glym143** [comment]
@Luccifer Hello! did you manage to update the framework?))

**Comment by Glym143** [comment]
@Luccifer Братан, ну обнови плиз ))

**Comment by Luccifer** [comment]
Updated
